services:
  db:
    image: postgres:16-alpine
    container_name: gm_generator_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"   

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gm_generator_backend
    restart: always
    depends_on:
      - db
    env_file: .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gm_generator_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "${APP_PORT:-3000}:80"    

volumes:
  postgres_data:
